### ISSUE TITLE
Request license and/or permission to use BestBase64EncoderDecoder

### ISSUE THREAD

**Issue by trev33b** [anonyco/BestBase64EncoderDecoder#1]
I wasn't sure how best to contact the author, but the company I work for would like to use BestBase64EncoderDecoder in our software and I'm seeking either written approval from the author or that a license be added to the distribution.  

Note: If you decide to use the DWTFYW license, I'll still need written approval because that license, despite its best intentions is broken.  As written, DWTFYW only covers the license text itself, not the software it's intended to address.

If it would be better to handle this via another communication channel, please let me know how best to contact you.

**Comment by anonyco** [comment]
Thank you for opening this Issue. Indeed, you are correct that there was no licence. Thus, I just posted up the Unlicence (at [COPYING.txt](https://github.com/anonyco/BestBase64EncoderDecoder/blob/master/COPYING.txt)). I hope that the Unlicence will not pose any problems for you. If you need to contact me over a more secure channel, then email me at [wowzeryest@gmail.com](mailto:wowzeryest@gmail.com). However, I am really bad at checking my email and I am a very forgetful person who cannot even remember what he had for breakfast this morning (a very unfortunate combination LOL). I shall try to check my email for you, but I cannot make any promises, sorry.

If you would like me to post up a different licence for you, then please just comment on this thread and I shall be happy to post up whatever licence you want me to post up.

Cheers! ~ Hope your software project goes well.

**Comment by trev33b** [comment]
Thank you very much!  I'll forward this to my legal team to make sure they're OK with everything.  If I have any issues, I'll reach out to you via email.  Otherwise, I'll close the issue.  I should know fairly quickly (within a day or so).

Lastly, it looks like you misspelled the name of the LICENSE.txt file (LISCENCE.txt).

**Comment by anonyco** [comment]
Thank you for catching that typo. I shall now close this github Issue request. Thank you again for spotting that critical flaw with the licensing. :+1:
